# Generated by Django 4.2.10 on 2025-02-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantdetect', '0002_search_data_input_image_search_data_output_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_data',
            name='output_image',
        ),
        migrations.RemoveField(
            model_name='search_data',
            name='predict_for',
        ),
        migrations.RemoveField(
            model_name='search_data',
            name='values_list',
        ),
        migrations.AddField(
            model_name='search_data',
            name='buy_link',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='search_data',
            name='description',
            field=models.FileField(max_length=400, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='search_data',
            name='disease_name',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='search_data',
            name='possible_steps',
            field=models.FileField(max_length=400, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='search_data',
            name='supplement_image',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='search_data',
            name='supplement_name',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blood_donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plantdetect.patient'),
        ),
        migrations.AlterField(
            model_name='search_data',
            name='input_image',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
    ]
